version: '3.4'

services:
  dapr-dashboard:
    image: "daprio/dashboard"
    ports:
      - "8080:8080"
    environment:
      - DAPR_API_TOKEN=my-secret
    volumes:
      - "./components/:/home/nonroot/.dapr/components"
    networks:
      - dapr-network

  placement:
    image: "daprio/dapr"
    command: ["./placement", "-port", "50005"]
    networks:
      - dapr-network

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - dapr-network

  orderservice:
    build:
      context: ./OrderService
      dockerfile: Dockerfile
    ports:
      - "5001:80"
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - ASPNETCORE_URLS=http://+:80
      - DAPR_HTTP_PORT=3500
      - DAPR_GRPC_PORT=50001
      - DAPR_API_TOKEN=my-secret
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/healthz"]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - dapr-network

  orderservice-dapr:
    image: "daprio/daprd:latest"
    command: ["./daprd",
      "-app-id", "orderservice",
      "-app-port", "80",
      "-dapr-http-port", "3500",
      "-dapr-grpc-port", "50001",
      "-placement-host-address", "placement:50005",
      "-resources-path", "/components",
      "--log-level", "debug"]
    volumes:
      - "./components/:/components"
    environment:
      - DAPR_API_TOKEN=my-secret
    depends_on:
      orderservice:
        condition: service_healthy
    network_mode: "service:orderservice"

  shippingservice:
    build:
      context: ./ShippingService
      dockerfile: Dockerfile
    ports:
      - "5002:80"
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - ASPNETCORE_URLS=http://+:80
      - DAPR_HTTP_PORT=3501
      - DAPR_GRPC_PORT=50002
      - DAPR_API_TOKEN=my-secret
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/healthz"]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - dapr-network

  shippingservice-dapr:
    image: "daprio/daprd:latest"
    command: ["./daprd",
      "-app-id", "shippingservice",
      "-app-port", "80",
      "-dapr-http-port", "3501",
      "-dapr-grpc-port", "50002",
      "-placement-host-address", "placement:50005",
      "-resources-path", "/components",
      "--log-level", "debug"]
    volumes:
      - "./components/:/components"
    environment:
      - DAPR_API_TOKEN=my-secret
    depends_on:
      shippingservice:
        condition: service_healthy
    network_mode: "service:shippingservice"

  notificationservice:
    build:
      context: ./NotificationService
      dockerfile: Dockerfile
    ports:
      - "5103:80"
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - ASPNETCORE_URLS=http://+:80
      - DAPR_HTTP_PORT=3502
      - DAPR_GRPC_PORT=50003
      - DAPR_API_TOKEN=my-secret
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/healthz"]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - dapr-network

  notificationservice-dapr:
    image: "daprio/daprd:latest"
    command: ["./daprd",
      "-app-id", "notificationservice",
      "-app-port", "80",
      "-dapr-http-port", "3502",
      "-dapr-grpc-port", "50003",
      "-placement-host-address", "placement:50005",
      "-resources-path", "/components",
      "--log-level", "debug"]
    volumes:
      - "./components/:/components"
    environment:
      - DAPR_API_TOKEN=my-secret
    depends_on:
      notificationservice:
        condition: service_healthy
    network_mode: "service:notificationservice"

networks:
  dapr-network:
