
version: '3.4'

services:
  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_NODE_ID: 1
      KAFKA_LISTENERS: 'PLAINTEXT://:9092,CONTROLLER://:9093,PLAINTEXT_HOST://:29092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
      CLUSTER_ID: 'a1b2c3d4-e5f6-7890-1234-567890abcdef'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTHORIZER_CLASS_NAME: 'org.apache.kafka.metadata.authorizer.StandardAuthorizer'
      KAFKA_SUPER_USERS: 'User:ANONYMOUS'
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
    command: >
      bash -c "
        if [ ! -f /tmp/kraft-combined-logs/meta.properties ]; then
          /bin/kafka-storage format --config /etc/kafka/server.properties --cluster-id a1b2c3d4-e5f6-7890-1234-567890abcdef --ignore-formatted;
        fi;
        /etc/confluent/docker/run"

  orderservice:
    build:
      context: ./OrderService
      dockerfile: Dockerfile
    ports:
      - "5001:80"
    depends_on:
      - kafka

  orderservice-dapr:
    image: "daprio/daprd:latest"
    command: ["./daprd",
      "-app-id", "orderservice",
      "-app-port", "80",
      "-dapr-http-port", "3500",
      "-components-path", "/components"]
    volumes:
      - "./components/:/components"
    depends_on:
      - orderservice
    network_mode: "service:orderservice"

  shippingservice:
    build:
      context: ./ShippingService
      dockerfile: Dockerfile
    ports:
      - "5002:80"

  shippingservice-dapr:
    image: "daprio/daprd:latest"
    command: ["./daprd",
      "-app-id", "shippingservice",
      "-app-port", "80",
      "-dapr-http-port", "3501",
      "-components-path", "/components"]
    volumes:
      - "./components/:/components"
    depends_on:
      - shippingservice
    network_mode: "service:shippingservice"

  notificationservice:
    build:
      context: ./NotificationService
      dockerfile: Dockerfile
    ports:
      - "5103:80"

  notificationservice-dapr:
    image: "daprio/daprd:latest"
    command: ["./daprd",
      "-app-id", "notificationservice",
      "-app-port", "80",
      "-dapr-http-port", "3502",
      "-components-path", "/components"]
    volumes:
      - "./components/:/components"
    depends_on:
      - notificationservice
    network_mode: "service:notificationservice"
